'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

<Assembly: Global.System.Data.Objects.DataClasses.EdmSchemaAttribute("2f535e59-4345-47b5-b6c6-3805a344be19"),  _
 Assembly: Global.System.Data.Objects.DataClasses.EdmRelationshipAttribute("NorthwindModel", "FK_Orders_Customers", "Customers", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(NorthwindModel.Customer), "Orders", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(NorthwindModel.Order)),  _
 Assembly: Global.System.Data.Objects.DataClasses.EdmRelationshipAttribute("NorthwindModel", "FK_Order_Details_Orders", "Orders", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(NorthwindModel.Order), "Order_Details", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(NorthwindModel.Order_Detail)),  _
 Assembly: Global.System.Data.Objects.DataClasses.EdmRelationshipAttribute("NorthwindModel", "FK_Order_Details_Products", "Products", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(NorthwindModel.Product), "Order_Details", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(NorthwindModel.Order_Detail))> 

'Original file name:
'Generation date: 5/29/2018 9:55:40 PM
Namespace NorthwindModel
    '''<summary>
    '''There are no comments for NorthwindModel.Customer in the schema.
    '''</summary>
    '''<KeyProperties>
    '''CustomerID
    '''</KeyProperties>
    <Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="NorthwindModel", Name:="Customer"),  _
     Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
     Global.System.Serializable()>  _
    Partial Public Class Customer
        Inherits Global.System.Data.Objects.DataClasses.EntityObject
        '''<summary>
        '''Create a new Customer object.
        '''</summary>
        '''<param name="customerID">Initial value of CustomerID.</param>
        '''<param name="companyName">Initial value of CompanyName.</param>
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Public Shared Function CreateCustomer(ByVal customerID As String, ByVal companyName As String) As Customer
            Dim customer As Customer = New Customer()
            customer.CustomerID = customerID
            customer.CompanyName = companyName
            Return customer
        End Function
        '''<summary>
        '''There are no comments for property CustomerID in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
         Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Public Property CustomerID() As String
            Get
                Return Me._CustomerID
            End Get
            Set
                Me.OnCustomerIDChanging(value)
                Me.ReportPropertyChanging("CustomerID")
                Me._CustomerID = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
                Me.ReportPropertyChanged("CustomerID")
                Me.OnCustomerIDChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Private _CustomerID As String
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnCustomerIDChanging(ByVal value As String)
        End Sub
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnCustomerIDChanged()
        End Sub
        '''<summary>
        '''There are no comments for property CompanyName in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
         Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Public Property CompanyName() As String
            Get
                Return Me._CompanyName
            End Get
            Set
                Me.OnCompanyNameChanging(value)
                Me.ReportPropertyChanging("CompanyName")
                Me._CompanyName = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
                Me.ReportPropertyChanged("CompanyName")
                Me.OnCompanyNameChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Private _CompanyName As String
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnCompanyNameChanging(ByVal value As String)
        End Sub
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnCompanyNameChanged()
        End Sub
        '''<summary>
        '''There are no comments for property ContactName in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Public Property ContactName() As String
            Get
                Return Me._ContactName
            End Get
            Set
                Me.OnContactNameChanging(value)
                Me.ReportPropertyChanging("ContactName")
                Me._ContactName = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
                Me.ReportPropertyChanged("ContactName")
                Me.OnContactNameChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Private _ContactName As String
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnContactNameChanging(ByVal value As String)
        End Sub
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnContactNameChanged()
        End Sub
        '''<summary>
        '''There are no comments for property ContactTitle in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Public Property ContactTitle() As String
            Get
                Return Me._ContactTitle
            End Get
            Set
                Me.OnContactTitleChanging(value)
                Me.ReportPropertyChanging("ContactTitle")
                Me._ContactTitle = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
                Me.ReportPropertyChanged("ContactTitle")
                Me.OnContactTitleChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Private _ContactTitle As String
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnContactTitleChanging(ByVal value As String)
        End Sub
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnContactTitleChanged()
        End Sub
        '''<summary>
        '''There are no comments for property Address in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Public Property Address() As String
            Get
                Return Me._Address
            End Get
            Set
                Me.OnAddressChanging(value)
                Me.ReportPropertyChanging("Address")
                Me._Address = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
                Me.ReportPropertyChanged("Address")
                Me.OnAddressChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Private _Address As String
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnAddressChanging(ByVal value As String)
        End Sub
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnAddressChanged()
        End Sub
        '''<summary>
        '''There are no comments for property City in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Public Property City() As String
            Get
                Return Me._City
            End Get
            Set
                Me.OnCityChanging(value)
                Me.ReportPropertyChanging("City")
                Me._City = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
                Me.ReportPropertyChanged("City")
                Me.OnCityChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Private _City As String
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnCityChanging(ByVal value As String)
        End Sub
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnCityChanged()
        End Sub
        '''<summary>
        '''There are no comments for property Region in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Public Property Region() As String
            Get
                Return Me._Region
            End Get
            Set
                Me.OnRegionChanging(value)
                Me.ReportPropertyChanging("Region")
                Me._Region = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
                Me.ReportPropertyChanged("Region")
                Me.OnRegionChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Private _Region As String
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnRegionChanging(ByVal value As String)
        End Sub
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnRegionChanged()
        End Sub
        '''<summary>
        '''There are no comments for property PostalCode in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Public Property PostalCode() As String
            Get
                Return Me._PostalCode
            End Get
            Set
                Me.OnPostalCodeChanging(value)
                Me.ReportPropertyChanging("PostalCode")
                Me._PostalCode = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
                Me.ReportPropertyChanged("PostalCode")
                Me.OnPostalCodeChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Private _PostalCode As String
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnPostalCodeChanging(ByVal value As String)
        End Sub
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnPostalCodeChanged()
        End Sub
        '''<summary>
        '''There are no comments for property Country in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Public Property Country() As String
            Get
                Return Me._Country
            End Get
            Set
                Me.OnCountryChanging(value)
                Me.ReportPropertyChanging("Country")
                Me._Country = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
                Me.ReportPropertyChanged("Country")
                Me.OnCountryChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Private _Country As String
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnCountryChanging(ByVal value As String)
        End Sub
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnCountryChanged()
        End Sub
        '''<summary>
        '''There are no comments for property Phone in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Public Property Phone() As String
            Get
                Return Me._Phone
            End Get
            Set
                Me.OnPhoneChanging(value)
                Me.ReportPropertyChanging("Phone")
                Me._Phone = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
                Me.ReportPropertyChanged("Phone")
                Me.OnPhoneChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Private _Phone As String
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnPhoneChanging(ByVal value As String)
        End Sub
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnPhoneChanged()
        End Sub
        '''<summary>
        '''There are no comments for property Fax in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Public Property Fax() As String
            Get
                Return Me._Fax
            End Get
            Set
                Me.OnFaxChanging(value)
                Me.ReportPropertyChanging("Fax")
                Me._Fax = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
                Me.ReportPropertyChanged("Fax")
                Me.OnFaxChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Private _Fax As String
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnFaxChanging(ByVal value As String)
        End Sub
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnFaxChanged()
        End Sub
        '''<summary>
        '''There are no comments for Orders in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("NorthwindModel", "FK_Orders_Customers", "Orders"),  _
         Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0"),  _
         Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
         Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Orders() As Global.System.Data.Objects.DataClasses.EntityCollection(Of Order)
            Get
                Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Order)("NorthwindModel.FK_Orders_Customers", "Orders")
            End Get
            Set
                If (Not (value) Is Nothing) Then
                    CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Order)("NorthwindModel.FK_Orders_Customers", "Orders", value)
                End If
            End Set
        End Property
    End Class
    '''<summary>
    '''There are no comments for NorthwindModel.Order_Detail in the schema.
    '''</summary>
    '''<KeyProperties>
    '''OrderID
    '''ProductID
    '''</KeyProperties>
    <Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="NorthwindModel", Name:="Order_Detail"),  _
     Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
     Global.System.Serializable()>  _
    Partial Public Class Order_Detail
        Inherits Global.System.Data.Objects.DataClasses.EntityObject
        '''<summary>
        '''Create a new Order_Detail object.
        '''</summary>
        '''<param name="orderID">Initial value of OrderID.</param>
        '''<param name="productID">Initial value of ProductID.</param>
        '''<param name="unitPrice">Initial value of UnitPrice.</param>
        '''<param name="quantity">Initial value of Quantity.</param>
        '''<param name="discount">Initial value of Discount.</param>
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Public Shared Function CreateOrder_Detail(ByVal orderID As Integer, ByVal productID As Integer, ByVal unitPrice As Decimal, ByVal quantity As Short, ByVal discount As Single) As Order_Detail
            Dim order_Detail As Order_Detail = New Order_Detail()
            order_Detail.OrderID = orderID
            order_Detail.ProductID = productID
            order_Detail.UnitPrice = unitPrice
            order_Detail.Quantity = quantity
            order_Detail.Discount = discount
            Return order_Detail
        End Function
        '''<summary>
        '''There are no comments for property OrderID in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
         Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Public Property OrderID() As Integer
            Get
                Return Me._OrderID
            End Get
            Set
                Me.OnOrderIDChanging(value)
                Me.ReportPropertyChanging("OrderID")
                Me._OrderID = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("OrderID")
                Me.OnOrderIDChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Private _OrderID As Integer
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnOrderIDChanging(ByVal value As Integer)
        End Sub
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnOrderIDChanged()
        End Sub
        '''<summary>
        '''There are no comments for property ProductID in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
         Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Public Property ProductID() As Integer
            Get
                Return Me._ProductID
            End Get
            Set
                Me.OnProductIDChanging(value)
                Me.ReportPropertyChanging("ProductID")
                Me._ProductID = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("ProductID")
                Me.OnProductIDChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Private _ProductID As Integer
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnProductIDChanging(ByVal value As Integer)
        End Sub
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnProductIDChanged()
        End Sub
        '''<summary>
        '''There are no comments for property UnitPrice in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
         Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Public Property UnitPrice() As Decimal
            Get
                Return Me._UnitPrice
            End Get
            Set
                Me.OnUnitPriceChanging(value)
                Me.ReportPropertyChanging("UnitPrice")
                Me._UnitPrice = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("UnitPrice")
                Me.OnUnitPriceChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Private _UnitPrice As Decimal
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnUnitPriceChanging(ByVal value As Decimal)
        End Sub
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnUnitPriceChanged()
        End Sub
        '''<summary>
        '''There are no comments for property Quantity in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
         Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Public Property Quantity() As Short
            Get
                Return Me._Quantity
            End Get
            Set
                Me.OnQuantityChanging(value)
                Me.ReportPropertyChanging("Quantity")
                Me._Quantity = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("Quantity")
                Me.OnQuantityChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Private _Quantity As Short
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnQuantityChanging(ByVal value As Short)
        End Sub
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnQuantityChanged()
        End Sub
        '''<summary>
        '''There are no comments for property Discount in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
         Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Public Property Discount() As Single
            Get
                Return Me._Discount
            End Get
            Set
                Me.OnDiscountChanging(value)
                Me.ReportPropertyChanging("Discount")
                Me._Discount = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("Discount")
                Me.OnDiscountChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Private _Discount As Single
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnDiscountChanging(ByVal value As Single)
        End Sub
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnDiscountChanged()
        End Sub
        '''<summary>
        '''There are no comments for Order in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("NorthwindModel", "FK_Order_Details_Orders", "Orders"),  _
         Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0"),  _
         Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
         Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Order() As Order
            Get
                Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Order)("NorthwindModel.FK_Order_Details_Orders", "Orders").Value
            End Get
            Set
                CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Order)("NorthwindModel.FK_Order_Details_Orders", "Orders").Value = value
            End Set
        End Property
        '''<summary>
        '''There are no comments for Order in the schema.
        '''</summary>
        <Global.System.ComponentModel.BrowsableAttribute(false),  _
         Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0"),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OrderReference() As Global.System.Data.Objects.DataClasses.EntityReference(Of Order)
            Get
                Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Order)("NorthwindModel.FK_Order_Details_Orders", "Orders")
            End Get
            Set
                If (Not (value) Is Nothing) Then
                    CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Order)("NorthwindModel.FK_Order_Details_Orders", "Orders", value)
                End If
            End Set
        End Property
        '''<summary>
        '''There are no comments for Product in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("NorthwindModel", "FK_Order_Details_Products", "Products"),  _
         Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0"),  _
         Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
         Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Product() As Product
            Get
                Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Product)("NorthwindModel.FK_Order_Details_Products", "Products").Value
            End Get
            Set
                CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Product)("NorthwindModel.FK_Order_Details_Products", "Products").Value = value
            End Set
        End Property
        '''<summary>
        '''There are no comments for Product in the schema.
        '''</summary>
        <Global.System.ComponentModel.BrowsableAttribute(false),  _
         Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0"),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ProductReference() As Global.System.Data.Objects.DataClasses.EntityReference(Of Product)
            Get
                Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Product)("NorthwindModel.FK_Order_Details_Products", "Products")
            End Get
            Set
                If (Not (value) Is Nothing) Then
                    CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Product)("NorthwindModel.FK_Order_Details_Products", "Products", value)
                End If
            End Set
        End Property
    End Class
    '''<summary>
    '''There are no comments for NorthwindModel.Order in the schema.
    '''</summary>
    '''<KeyProperties>
    '''OrderID
    '''</KeyProperties>
    <Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="NorthwindModel", Name:="Order"),  _
     Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
     Global.System.Serializable()>  _
    Partial Public Class Order
        Inherits Global.System.Data.Objects.DataClasses.EntityObject
        '''<summary>
        '''Create a new Order object.
        '''</summary>
        '''<param name="orderID">Initial value of OrderID.</param>
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Public Shared Function CreateOrder(ByVal orderID As Integer) As Order
            Dim order As Order = New Order()
            order.OrderID = orderID
            Return order
        End Function
        '''<summary>
        '''There are no comments for property OrderID in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
         Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Public Property OrderID() As Integer
            Get
                Return Me._OrderID
            End Get
            Set
                Me.OnOrderIDChanging(value)
                Me.ReportPropertyChanging("OrderID")
                Me._OrderID = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("OrderID")
                Me.OnOrderIDChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Private _OrderID As Integer
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnOrderIDChanging(ByVal value As Integer)
        End Sub
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnOrderIDChanged()
        End Sub
        '''<summary>
        '''There are no comments for property EmployeeID in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Public Property EmployeeID() As Global.System.Nullable(Of Integer)
            Get
                Return Me._EmployeeID
            End Get
            Set
                Me.OnEmployeeIDChanging(value)
                Me.ReportPropertyChanging("EmployeeID")
                Me._EmployeeID = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("EmployeeID")
                Me.OnEmployeeIDChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Private _EmployeeID As Global.System.Nullable(Of Integer)
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnEmployeeIDChanging(ByVal value As Global.System.Nullable(Of Integer))
        End Sub
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnEmployeeIDChanged()
        End Sub
        '''<summary>
        '''There are no comments for property OrderDate in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Public Property OrderDate() As Global.System.Nullable(Of Date)
            Get
                Return Me._OrderDate
            End Get
            Set
                Me.OnOrderDateChanging(value)
                Me.ReportPropertyChanging("OrderDate")
                Me._OrderDate = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("OrderDate")
                Me.OnOrderDateChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Private _OrderDate As Global.System.Nullable(Of Date)
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnOrderDateChanging(ByVal value As Global.System.Nullable(Of Date))
        End Sub
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnOrderDateChanged()
        End Sub
        '''<summary>
        '''There are no comments for property RequiredDate in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Public Property RequiredDate() As Global.System.Nullable(Of Date)
            Get
                Return Me._RequiredDate
            End Get
            Set
                Me.OnRequiredDateChanging(value)
                Me.ReportPropertyChanging("RequiredDate")
                Me._RequiredDate = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("RequiredDate")
                Me.OnRequiredDateChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Private _RequiredDate As Global.System.Nullable(Of Date)
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnRequiredDateChanging(ByVal value As Global.System.Nullable(Of Date))
        End Sub
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnRequiredDateChanged()
        End Sub
        '''<summary>
        '''There are no comments for property ShippedDate in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Public Property ShippedDate() As Global.System.Nullable(Of Date)
            Get
                Return Me._ShippedDate
            End Get
            Set
                Me.OnShippedDateChanging(value)
                Me.ReportPropertyChanging("ShippedDate")
                Me._ShippedDate = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("ShippedDate")
                Me.OnShippedDateChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Private _ShippedDate As Global.System.Nullable(Of Date)
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnShippedDateChanging(ByVal value As Global.System.Nullable(Of Date))
        End Sub
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnShippedDateChanged()
        End Sub
        '''<summary>
        '''There are no comments for property ShipVia in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Public Property ShipVia() As Global.System.Nullable(Of Integer)
            Get
                Return Me._ShipVia
            End Get
            Set
                Me.OnShipViaChanging(value)
                Me.ReportPropertyChanging("ShipVia")
                Me._ShipVia = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("ShipVia")
                Me.OnShipViaChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Private _ShipVia As Global.System.Nullable(Of Integer)
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnShipViaChanging(ByVal value As Global.System.Nullable(Of Integer))
        End Sub
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnShipViaChanged()
        End Sub
        '''<summary>
        '''There are no comments for property Freight in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Public Property Freight() As Global.System.Nullable(Of Decimal)
            Get
                Return Me._Freight
            End Get
            Set
                Me.OnFreightChanging(value)
                Me.ReportPropertyChanging("Freight")
                Me._Freight = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("Freight")
                Me.OnFreightChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Private _Freight As Global.System.Nullable(Of Decimal)
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnFreightChanging(ByVal value As Global.System.Nullable(Of Decimal))
        End Sub
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnFreightChanged()
        End Sub
        '''<summary>
        '''There are no comments for property ShipName in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Public Property ShipName() As String
            Get
                Return Me._ShipName
            End Get
            Set
                Me.OnShipNameChanging(value)
                Me.ReportPropertyChanging("ShipName")
                Me._ShipName = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
                Me.ReportPropertyChanged("ShipName")
                Me.OnShipNameChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Private _ShipName As String
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnShipNameChanging(ByVal value As String)
        End Sub
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnShipNameChanged()
        End Sub
        '''<summary>
        '''There are no comments for property ShipAddress in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Public Property ShipAddress() As String
            Get
                Return Me._ShipAddress
            End Get
            Set
                Me.OnShipAddressChanging(value)
                Me.ReportPropertyChanging("ShipAddress")
                Me._ShipAddress = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
                Me.ReportPropertyChanged("ShipAddress")
                Me.OnShipAddressChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Private _ShipAddress As String
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnShipAddressChanging(ByVal value As String)
        End Sub
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnShipAddressChanged()
        End Sub
        '''<summary>
        '''There are no comments for property ShipCity in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Public Property ShipCity() As String
            Get
                Return Me._ShipCity
            End Get
            Set
                Me.OnShipCityChanging(value)
                Me.ReportPropertyChanging("ShipCity")
                Me._ShipCity = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
                Me.ReportPropertyChanged("ShipCity")
                Me.OnShipCityChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Private _ShipCity As String
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnShipCityChanging(ByVal value As String)
        End Sub
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnShipCityChanged()
        End Sub
        '''<summary>
        '''There are no comments for property ShipRegion in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Public Property ShipRegion() As String
            Get
                Return Me._ShipRegion
            End Get
            Set
                Me.OnShipRegionChanging(value)
                Me.ReportPropertyChanging("ShipRegion")
                Me._ShipRegion = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
                Me.ReportPropertyChanged("ShipRegion")
                Me.OnShipRegionChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Private _ShipRegion As String
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnShipRegionChanging(ByVal value As String)
        End Sub
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnShipRegionChanged()
        End Sub
        '''<summary>
        '''There are no comments for property ShipPostalCode in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Public Property ShipPostalCode() As String
            Get
                Return Me._ShipPostalCode
            End Get
            Set
                Me.OnShipPostalCodeChanging(value)
                Me.ReportPropertyChanging("ShipPostalCode")
                Me._ShipPostalCode = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
                Me.ReportPropertyChanged("ShipPostalCode")
                Me.OnShipPostalCodeChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Private _ShipPostalCode As String
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnShipPostalCodeChanging(ByVal value As String)
        End Sub
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnShipPostalCodeChanged()
        End Sub
        '''<summary>
        '''There are no comments for property ShipCountry in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Public Property ShipCountry() As String
            Get
                Return Me._ShipCountry
            End Get
            Set
                Me.OnShipCountryChanging(value)
                Me.ReportPropertyChanging("ShipCountry")
                Me._ShipCountry = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
                Me.ReportPropertyChanged("ShipCountry")
                Me.OnShipCountryChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Private _ShipCountry As String
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnShipCountryChanging(ByVal value As String)
        End Sub
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnShipCountryChanged()
        End Sub
        '''<summary>
        '''There are no comments for Customer in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("NorthwindModel", "FK_Orders_Customers", "Customers"),  _
         Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0"),  _
         Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
         Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Customer() As Customer
            Get
                Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Customer)("NorthwindModel.FK_Orders_Customers", "Customers").Value
            End Get
            Set
                CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Customer)("NorthwindModel.FK_Orders_Customers", "Customers").Value = value
            End Set
        End Property
        '''<summary>
        '''There are no comments for Customer in the schema.
        '''</summary>
        <Global.System.ComponentModel.BrowsableAttribute(false),  _
         Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0"),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CustomerReference() As Global.System.Data.Objects.DataClasses.EntityReference(Of Customer)
            Get
                Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Customer)("NorthwindModel.FK_Orders_Customers", "Customers")
            End Get
            Set
                If (Not (value) Is Nothing) Then
                    CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Customer)("NorthwindModel.FK_Orders_Customers", "Customers", value)
                End If
            End Set
        End Property
        '''<summary>
        '''There are no comments for Order_Details in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("NorthwindModel", "FK_Order_Details_Orders", "Order_Details"),  _
         Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0"),  _
         Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
         Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Order_Details() As Global.System.Data.Objects.DataClasses.EntityCollection(Of Order_Detail)
            Get
                Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Order_Detail)("NorthwindModel.FK_Order_Details_Orders", "Order_Details")
            End Get
            Set
                If (Not (value) Is Nothing) Then
                    CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Order_Detail)("NorthwindModel.FK_Order_Details_Orders", "Order_Details", value)
                End If
            End Set
        End Property
    End Class
    '''<summary>
    '''There are no comments for NorthwindModel.Product in the schema.
    '''</summary>
    '''<KeyProperties>
    '''ProductID
    '''</KeyProperties>
    <Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="NorthwindModel", Name:="Product"),  _
     Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
     Global.System.Serializable()>  _
    Partial Public Class Product
        Inherits Global.System.Data.Objects.DataClasses.EntityObject
        '''<summary>
        '''Create a new Product object.
        '''</summary>
        '''<param name="productID">Initial value of ProductID.</param>
        '''<param name="productName">Initial value of ProductName.</param>
        '''<param name="discontinued">Initial value of Discontinued.</param>
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Public Shared Function CreateProduct(ByVal productID As Integer, ByVal productName As String, ByVal discontinued As Boolean) As Product
            Dim product As Product = New Product()
            product.ProductID = productID
            product.ProductName = productName
            product.Discontinued = discontinued
            Return product
        End Function
        '''<summary>
        '''There are no comments for property ProductID in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
         Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Public Property ProductID() As Integer
            Get
                Return Me._ProductID
            End Get
            Set
                Me.OnProductIDChanging(value)
                Me.ReportPropertyChanging("ProductID")
                Me._ProductID = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("ProductID")
                Me.OnProductIDChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Private _ProductID As Integer
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnProductIDChanging(ByVal value As Integer)
        End Sub
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnProductIDChanged()
        End Sub
        '''<summary>
        '''There are no comments for property ProductName in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
         Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Public Property ProductName() As String
            Get
                Return Me._ProductName
            End Get
            Set
                Me.OnProductNameChanging(value)
                Me.ReportPropertyChanging("ProductName")
                Me._ProductName = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
                Me.ReportPropertyChanged("ProductName")
                Me.OnProductNameChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Private _ProductName As String
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnProductNameChanging(ByVal value As String)
        End Sub
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnProductNameChanged()
        End Sub
        '''<summary>
        '''There are no comments for property SupplierID in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Public Property SupplierID() As Global.System.Nullable(Of Integer)
            Get
                Return Me._SupplierID
            End Get
            Set
                Me.OnSupplierIDChanging(value)
                Me.ReportPropertyChanging("SupplierID")
                Me._SupplierID = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("SupplierID")
                Me.OnSupplierIDChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Private _SupplierID As Global.System.Nullable(Of Integer)
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnSupplierIDChanging(ByVal value As Global.System.Nullable(Of Integer))
        End Sub
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnSupplierIDChanged()
        End Sub
        '''<summary>
        '''There are no comments for property CategoryID in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Public Property CategoryID() As Global.System.Nullable(Of Integer)
            Get
                Return Me._CategoryID
            End Get
            Set
                Me.OnCategoryIDChanging(value)
                Me.ReportPropertyChanging("CategoryID")
                Me._CategoryID = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("CategoryID")
                Me.OnCategoryIDChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Private _CategoryID As Global.System.Nullable(Of Integer)
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnCategoryIDChanging(ByVal value As Global.System.Nullable(Of Integer))
        End Sub
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnCategoryIDChanged()
        End Sub
        '''<summary>
        '''There are no comments for property QuantityPerUnit in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Public Property QuantityPerUnit() As String
            Get
                Return Me._QuantityPerUnit
            End Get
            Set
                Me.OnQuantityPerUnitChanging(value)
                Me.ReportPropertyChanging("QuantityPerUnit")
                Me._QuantityPerUnit = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
                Me.ReportPropertyChanged("QuantityPerUnit")
                Me.OnQuantityPerUnitChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Private _QuantityPerUnit As String
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnQuantityPerUnitChanging(ByVal value As String)
        End Sub
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnQuantityPerUnitChanged()
        End Sub
        '''<summary>
        '''There are no comments for property UnitPrice in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Public Property UnitPrice() As Global.System.Nullable(Of Decimal)
            Get
                Return Me._UnitPrice
            End Get
            Set
                Me.OnUnitPriceChanging(value)
                Me.ReportPropertyChanging("UnitPrice")
                Me._UnitPrice = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("UnitPrice")
                Me.OnUnitPriceChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Private _UnitPrice As Global.System.Nullable(Of Decimal)
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnUnitPriceChanging(ByVal value As Global.System.Nullable(Of Decimal))
        End Sub
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnUnitPriceChanged()
        End Sub
        '''<summary>
        '''There are no comments for property UnitsInStock in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Public Property UnitsInStock() As Global.System.Nullable(Of Short)
            Get
                Return Me._UnitsInStock
            End Get
            Set
                Me.OnUnitsInStockChanging(value)
                Me.ReportPropertyChanging("UnitsInStock")
                Me._UnitsInStock = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("UnitsInStock")
                Me.OnUnitsInStockChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Private _UnitsInStock As Global.System.Nullable(Of Short)
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnUnitsInStockChanging(ByVal value As Global.System.Nullable(Of Short))
        End Sub
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnUnitsInStockChanged()
        End Sub
        '''<summary>
        '''There are no comments for property UnitsOnOrder in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Public Property UnitsOnOrder() As Global.System.Nullable(Of Short)
            Get
                Return Me._UnitsOnOrder
            End Get
            Set
                Me.OnUnitsOnOrderChanging(value)
                Me.ReportPropertyChanging("UnitsOnOrder")
                Me._UnitsOnOrder = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("UnitsOnOrder")
                Me.OnUnitsOnOrderChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Private _UnitsOnOrder As Global.System.Nullable(Of Short)
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnUnitsOnOrderChanging(ByVal value As Global.System.Nullable(Of Short))
        End Sub
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnUnitsOnOrderChanged()
        End Sub
        '''<summary>
        '''There are no comments for property ReorderLevel in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Public Property ReorderLevel() As Global.System.Nullable(Of Short)
            Get
                Return Me._ReorderLevel
            End Get
            Set
                Me.OnReorderLevelChanging(value)
                Me.ReportPropertyChanging("ReorderLevel")
                Me._ReorderLevel = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("ReorderLevel")
                Me.OnReorderLevelChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Private _ReorderLevel As Global.System.Nullable(Of Short)
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnReorderLevelChanging(ByVal value As Global.System.Nullable(Of Short))
        End Sub
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnReorderLevelChanged()
        End Sub
        '''<summary>
        '''There are no comments for property Discontinued in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
         Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Public Property Discontinued() As Boolean
            Get
                Return Me._Discontinued
            End Get
            Set
                Me.OnDiscontinuedChanging(value)
                Me.ReportPropertyChanging("Discontinued")
                Me._Discontinued = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("Discontinued")
                Me.OnDiscontinuedChanged
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Private _Discontinued As Boolean
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnDiscontinuedChanging(ByVal value As Boolean)
        End Sub
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Partial Private Sub OnDiscontinuedChanged()
        End Sub
        '''<summary>
        '''There are no comments for Order_Details in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("NorthwindModel", "FK_Order_Details_Products", "Order_Details"),  _
         Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0"),  _
         Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
         Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Order_Details() As Global.System.Data.Objects.DataClasses.EntityCollection(Of Order_Detail)
            Get
                Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Order_Detail)("NorthwindModel.FK_Order_Details_Products", "Order_Details")
            End Get
            Set
                If (Not (value) Is Nothing) Then
                    CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Order_Detail)("NorthwindModel.FK_Order_Details_Products", "Order_Details", value)
                End If
            End Set
        End Property
    End Class
    '''<summary>
    '''There are no comments for NorthwindEntities in the schema.
    '''</summary>
    Partial Public Class NorthwindEntities
        Inherits Global.System.Data.Objects.ObjectContext
        '''<summary>
        '''Initializes a new NorthwindEntities object using the connection string found in the 'NorthwindEntities' section of the application configuration file.
        '''</summary>
        Public Sub New()
            MyBase.New("name=NorthwindEntities", "NorthwindEntities")
            Me.OnContextCreated
        End Sub
        '''<summary>
        '''Initialize a new NorthwindEntities object.
        '''</summary>
        Public Sub New(ByVal connectionString As String)
            MyBase.New(connectionString, "NorthwindEntities")
            Me.OnContextCreated
        End Sub
        '''<summary>
        '''Initialize a new NorthwindEntities object.
        '''</summary>
        Public Sub New(ByVal connection As Global.System.Data.EntityClient.EntityConnection)
            MyBase.New(connection, "NorthwindEntities")
            Me.OnContextCreated
        End Sub
        Partial Private Sub OnContextCreated()
        End Sub
        '''<summary>
        '''There are no comments for Customers in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Public ReadOnly Property Customers() As Global.System.Data.Objects.ObjectQuery(Of Customer)
            Get
                If (Me._Customers Is Nothing) Then
                    Me._Customers = MyBase.CreateQuery(Of Customer)("[Customers]")
                End If
                Return Me._Customers
            End Get
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Private _Customers As Global.System.Data.Objects.ObjectQuery(Of Customer)
        '''<summary>
        '''There are no comments for Order_Details in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Public ReadOnly Property Order_Details() As Global.System.Data.Objects.ObjectQuery(Of Order_Detail)
            Get
                If (Me._Order_Details Is Nothing) Then
                    Me._Order_Details = MyBase.CreateQuery(Of Order_Detail)("[Order_Details]")
                End If
                Return Me._Order_Details
            End Get
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Private _Order_Details As Global.System.Data.Objects.ObjectQuery(Of Order_Detail)
        '''<summary>
        '''There are no comments for Orders in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Public ReadOnly Property Orders() As Global.System.Data.Objects.ObjectQuery(Of Order)
            Get
                If (Me._Orders Is Nothing) Then
                    Me._Orders = MyBase.CreateQuery(Of Order)("[Orders]")
                End If
                Return Me._Orders
            End Get
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Private _Orders As Global.System.Data.Objects.ObjectQuery(Of Order)
        '''<summary>
        '''There are no comments for Products in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Public ReadOnly Property Products() As Global.System.Data.Objects.ObjectQuery(Of Product)
            Get
                If (Me._Products Is Nothing) Then
                    Me._Products = MyBase.CreateQuery(Of Product)("[Products]")
                End If
                Return Me._Products
            End Get
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Private _Products As Global.System.Data.Objects.ObjectQuery(Of Product)
        '''<summary>
        '''There are no comments for Customers in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Public Sub AddToCustomers(ByVal customer As Customer)
            MyBase.AddObject("Customers", customer)
        End Sub
        '''<summary>
        '''There are no comments for Order_Details in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Public Sub AddToOrder_Details(ByVal order_Detail As Order_Detail)
            MyBase.AddObject("Order_Details", order_Detail)
        End Sub
        '''<summary>
        '''There are no comments for Orders in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Public Sub AddToOrders(ByVal order As Order)
            MyBase.AddObject("Orders", order)
        End Sub
        '''<summary>
        '''There are no comments for Products in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
        Public Sub AddToProducts(ByVal product As Product)
            MyBase.AddObject("Products", product)
        End Sub
    End Class
End Namespace
